#ifndef LOGGING_STATES_H
#define LOGGING_STATES_H

#include <mpe.h>


extern int INFERENCE_INIT_START, INFERENCE_INIT_END;

extern int INFERENCE_ON2VN_START, INFERENCE_ON2VN_END;
extern int ON2VN_SEND_ACTIVATIONS_START, ON2VN_SEND_ACTIVATIONS_END;
extern int ON2VN_UPDATE_VNS_ACTIVATED_BY_ONS_START, ON2VN_UPDATE_VNS_ACTIVATED_BY_ONS_END;
extern int ON2VN_FIND_OWN_STARTING_POINTS_START, ON2VN_FIND_OWN_STARTING_POINTS_END;
extern int ON2VN_DISTRIBUTE_VN_STARTING_POINTS_START, ON2VN_DISTRIBUTE_VN_STARTING_POINTS_END;
extern int ON2VN_CALCULATE_VN_ACTIVATIONS_START, ON2VN_CALCULATE_VN_ACTIVATIONS_END;
extern int ON2VN_FREE_MEMORY_START, ON2VN_FREE_MEMORY_END;

extern int SEND_ACTIVATIONS_SEND_VNG_START, SEND_ACTIVATIONS_SEND_VNG_END;
extern int SEND_ACTIVATIONS_SEND_SINGLE_ON_START, SEND_ACTIVATIONS_SEND_SINGLE_ON_END;

extern int INFERENCE_VN2ON_START, INFERENCE_VN2ON_END;

void init_events();

#endif